version: 2.1
jobs:
    build:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - restore_cache:
                key: project-cache
            - run: cargo install wasm-pack
            - run: wasm-pack build
            - save_cache:
                key: project-cache
                paths:
                    - "~/.cargo"
                    - "./target"
            - persist_to_workspace:
                root: /home/circleci/project
                paths:
                    - pkg
    deploy:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project/pkg
            - run: pwd
            - run: ls
            - run: cd pkg && ls
            - run: npm --prefix web install
            - run: npm --prefix web run build

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build