version: 2.1

executors:
    rust-executor:
        docker:
            - image: circleci/rust:latest
    node-executor:
        docker:
            - image: circleci/node:latest

jobs:
    build:
        executor: rust-executor
        steps:
            - checkout
            - run: cargo install wasm-pack
            - run: wasm-pack build
            - persist_to_workspace:
                root: pkg
    deploy:
        executor: node-executor
        steps:
            - checkout
            - attach_workspace:
                at: pkg
            - run: npm --prefix web install
            - run: npm --prefix web run build

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build