version: 2.1
jobs:
    build:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run: pwd
            - run: cargo install wasm-pack
            - run: wasm-pack build
            - persist_to_workspace:
                root: /
                path: pkg
    deploy:
        docker:
            - image: circleci/node:latest
        steps:
            - attach_workspace:
                at: /
            - run: npm --prefix web install
            - run: npm --prefix web run build

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build