version: 2.1
jobs:
    build:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run: cargo install wasm-pack
            - run: wasm-pack build
    deploy:
        docker:
            - image: circleci/node:latest
        workdir: web
        steps:
            - checkout
            - run: npm install
            - run: npm run build

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build